  sonar.projectKey=rookiejoel
  sonar.organization="Suttanop Chanah"
  sonar.projectName=AThena
  sonar.sources=frontend/src,backend/src
  sonar.exclusions=**/node_modules/**,**/reports/**,**/*.test.*